# Unit system
UNITS_PER_TILE = 32
PIXELS_PER_TILE = 64
PIXELS_PER_UNIT = PIXELS_PER_TILE / UNITS_PER_TILE  # 2.0

HITBOX_SIZE = 28  # in units

# Render (for compatibility)
TILE_SIZE = PIXELS_PER_TILE

# Physics (all values in units per second)
# https://ddnet.org/settingscommands/
# Engine uses Y-up coordinate system
AIR_CONTROL_ACCEL = 1.5
AIR_CONTROL_SPEED = 5.0
AIR_FRICTION = 0.95
AIR_JUMP_IMPULSE = 12.0
GRAVITY = 0.5
GROUND_CONTROL_ACCEL = 2.0
GROUND_CONTROL_SPEED = 10.0
GROUND_ELASTICITY_X = 0.0
GROUND_ELASTICITY_Y = 0.0
GROUND_FRICTION = 0.5
GROUND_JUMP_IMPULSE = 13.2

HOOK_DRAG_ACCEL = 3.0
HOOK_DRAG_SPEED = 15.0
HOOK_DURATION = 1.25
HOOK_FIRE_SPEED = 80
HOOK_LENGTH = 380.0

VELRAMP_CURVATURE = 1.4
VELRAMP_START = 2000.0
VELRAMP_RANGE = 550.0